config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, :controllers => {registrations: 'registrations'}
  devise_for :providers,  :controllers => {registrations: 'registrations'}
   get 'provider_terms' => 'provider_terms_of_use#index'
   get 'privacy' => 'privacy_policy#index'
   get 'terms' => 'terms_of_use#index'
   get 'provider/:id' => 'provider#show'
   get 'funds_required' => 'funds#funds_required'
   get 'funds_submit' => 'funds#funds_submit'
   resources :providers do
     resources :reviews
  end
   resources :clients do
     resources :reviews
  end
  
     resources :funds
   get 'providers/:id/show_profile_image' => 'providers#show_profile_image'
   root 'home#index'

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/views/layouts/check_provider_status/_check_provider_status.html.erb
<% if @provider.status == 2 %>

	<% if client_signed_in? %>
		<% if current_client.fund == nil || current_client.fund.avail_amount == nil || current_client.fund.avail_amount < 10 %>
			<%= link_to funds_required_path do %>
			<div class="gridLinkSchedBox gridLinkBox">
				Talk Now!
			</div>
			<%end%>
		<%elsif current_client.fund != nil && current_client.fund.avail_amount != nil && current_client.fund.avail_amount > 9 %>
			<%= link_to funds_submit_path do %>
			<div class="gridLinkSchedBox gridLinkBox">
				Talk Now!
			</div>
			<%end%>
		<%end%>
	<% else%>
		<%= link_to new_client_session_path do %>
		<div class="gridLinkSchedBox gridLinkBox">
			Talk Now!
		</div>
		<%end%>
	<%end%>
<%elsif @provider.status == 1 || @provider.status == 3 %>
<div class="gridLinkSchedBox gridLinkBox">
	Email This Provider
</div>
<%end%>