config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, :controllers => {registrations: 'registrations'}
  devise_for :providers,  :controllers => {registrations: 'registrations'}
   get 'provider_terms' => 'provider_terms_of_use#index'
   get 'privacy' => 'privacy_policy#index'
   get 'terms' => 'terms_of_use#index'
   get 'provider/:id' => 'provider#show'
   get 'funds_required' => 'funds#funds_required'
   get 'funds_submit' => 'funds#funds_submit'
   resources :providers do
     resources :reviews
  end
   resources :clients do
     resources :reviews
  end
  
     resources :funds
   get 'providers/:id/show_profile_image' => 'providers#show_profile_image'
   root 'home#index'

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/views/layouts/_account_cancel.html.erb
<div>
	<br/>
	<h2 class="label">Close Account</h2>
</div>
<div class="signUpBlockDiv">
	<div class="signButtonDiv">

		<%= button_to "Cancel my account", registration_path(resource_name), {data: { confirm: "This action is not reversible.\nClosing your account completely removes your profile and all associated information from our systems.\n\nTo continue closing your account, press OK. If you wish to keep your account open, press Cancel." },  method: :delete, class: "submit override" } %>

	</div>
</div>

app/views/layouts/_disclaimer.html.erb
<div class="footer">
	<div class="footerContent label">
		Online Counseling is not appropriate for crisis situations nor emergencies. If you are having an emergency,
		call 911 or go to the nearest emergency room.
		If you are in crisis, call the National Suicide Prevention Lifeline, a free, 24-hour hotline, at 1.800.273.8255.
		<div class="footerLinkHolder">
			<div class="label footerLinks">
				<%= link_to "Client Terms of Use", terms_path %>
			</div>
			<div class="label footerLinks">
				<%= link_to "Provider Terms of Use", provider_terms_path %>
			</div>			
			<div class="label footerLinks">
				<%= link_to "Privacy Policy", privacy_path %>
			</div>
		</div>
	</div>

</div>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="innerHeader">
		<%= link_to image_tag('logo.png'), root_path%>
	</div>
	<%= render 'layouts/devise_status'%>
	<% if client_signed_in? || provider_signed_in?%>
	<% if current_client %>
	<div class="actionBarLine">
		<div class="actionBar">
			<div>
				<span><%= link_to destroy_client_session_path,
					method: :delete do%>Sign Out<%end%> </span>
			</div>
			<div>
				<span><%= link_to(edit_client_registration_path) do %>Edit Profile<%end%></span>
			</div>
			<% if client_signed_in? %>
			<div>
				<span><%= link_to(providers_path) do %>Find A Counselor<%end%></span>
			</div>
			<%end%>
			
			
			<div class="actionDivStatus">
				Client Signed in as: <%= current_client.first_name %> <%= current_client.last_name%>
			</div>

		</div>
	</div>
	<% elsif current_provider %>
	<div class="actionBarLine">
		<div class="actionBar">
			<div>
				<span><%= link_to destroy_provider_session_path,
					method: :delete do%>Sign Out<%end%> </span>
			</div>
			<div>
				<span><%= link_to(edit_provider_registration_path) do %>Edit Profile<%end%></span>
			</div>
			<div>
				<% @provider = current_provider %>
				<%= form_for @provider, as: @post, method: :patch do |p| %>	
					Status: <%= p.select(:status, options_for_select([['Offline',1], ['Available',2], ['Unavailable',3]], selected: p.object.status),{}, {onchange: 'this.form.submit()',  class: 'status_combo_box'}) %>
				<%end%>
			</div>
			<div class="actionDivStatus">
				<span class="label"> Provider Signed in as: <%= current_provider.first_name %> <%= current_provider.last_name%> </span>
			</div>
		</div>
	</div>
	<%end%>
	<%end%>
</div>

<div class="PostHeader">
	<% if client_signed_in? %>
	<%= link_to destroy_client_session_path,
	method: :delete do%>
	<div class="menu_item">
		<span class="vMiddle">Sign Out</span>
	</div>
	<%end%>
	<%= link_to(providers_path) do %>
	<div class="menu_item">
		<span class="vMiddle">Find A Counselor</span>
	</div>
	<%end%>
	<%= link_to(edit_client_registration_path) do %>
	<div class="menu_item">
		<span class="vMiddle">Edit Profile</span>
	</div>
	<%end%>
	<% elsif provider_signed_in? %>
	<%= link_to destroy_provider_session_path,
	method: :delete do%>
	<div class="menu_item">
		<span class="vMiddle">Sign Out</span>
	</div>
	<%end%>
	<%= link_to(edit_provider_registration_path) do %>
	<div class="menu_item">
		<span class="vMiddle">Edit Profile</span>
	</div>
	<%end%>
	<% else  %>
	<%= link_to(new_client_session_path) do%>
	<div class="menu_item">
		<span class="vMiddle">Client Sign In</span>
	</div>
	<%end%>
	<%= link_to(new_client_registration_path) do %>
	<div class="menu_item">
		<span class="vMiddle">Client Register</span>
	</div>
	<%end%>

	<%= link_to(new_provider_session_path) do %>
	<div class="menu_item">
		<span class="vMiddle">Provider Sign In</span>
	</div>
	<%end%>
	<%= link_to(new_provider_registration_path) do %>
	<div class="menu_item">
		<span class="vMiddle">Provider Register</span>
	</div>
	<%end%>
	<%end%>

</div>


app/views/layouts/_personal_info.html.erb
<div class="signUpInputDiv label">
	<%= devise_error_messages! %>
</div>
<div class="signUpBlockDiv">

	<h2 class="label">Personal Information</h2>
</div>
<% if provider_signed_in? %>
<div class="label">
	Addresses are used for billing purposes only.
	<br/>
	Phone Numbers are disclosed to clients only for providers that elect to provide phone services
	<br/>
	<br/>
</div>
<%else%>
<div class="label">
	Addresses and Phone Numbers are used for billing purposes only.
	<br/>
	ThisSite does not disclose client contact information to others.
	<br/>
	<br/>
</div>
<%end%>
<% if resource.new_record? %>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :first_name, "*First Name:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :first_name, {class: 'text_field',autofocus: true}  %>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :last_name, "*Last Name:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :last_name, {class: 'text_field'}  %>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :birthdate, "*Birthdate:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">
		<%= f.date_select :birthdate, {start_year: 1900, end_year: Date.today.year - 3, order: [:month, :day, :year], default: { year: 1975}}, {class: 'combo_box'} %>
	</div>
</div>
<%else%>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :first_name, "Name:",{ class: 'label'} %>
	</div>
	<div class="signUpInputDiv signUpLabelDiv">
		<%= f.label :first_name, f.object.first_name + " " + f.object.last_name, {class: 'label'} %>
	</div>
</div>
<%end%>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :address1, "*Address 1", {class: 'label'}%>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :address1, {class: 'text_field'}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :address2, "Address 2", {class: 'label'}%>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :address2, {class: 'text_field'}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :city, "*City", {class: 'label'}%>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :city, {class: 'text_field'}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :state, "*State", {class: 'label'}%>
	</div>
	<div class="signUpInputDiv">
		<%= f.select(:state, options_for_select(us_states, selected: f.object.state),{}, {class: 'combo_box'}) %>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :zip, "*Zip Code", {class: 'label'}%>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :zip, {class: 'text_field'}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :email, "*Email Address:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">

		<%= f.email_field :email, {class: 'text_field'} %>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :phone, "*Phone Number:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">

		<%= f.telephone_field :phone, { class: 'text_field'} %>
	</div>
</div>

<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :alt_phone, "Alternate Number:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">

		<%= f.telephone_field :alt_phone, { class: 'text_field'} %>
	</div>
</div>
<% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		Currently waiting confirmation for: <%= resource.unconfirmed_email %>
	</div>
</div>
<% end %>

app/views/layouts/_provider_grid.html.erb
<div class="label">
	<%= form_tag providers_path, method: 'get' %>
	Sort By: <%= select_tag(:sort_by, options_for_select(['Highest Rating','Lowest Rate', 'Available By Phone', 'Available By Chat', 'Available By Email'], params[:sort_by]), onchange: 'this.form.submit()',  class: 'combo_box') %>
	<%= link_to "Advanced Search"%>
</div>
<div class="providerGrid">
	<% @providers.each do |p| %>
	<div class="providerRow">
		<div class="providerHeaderRow">
			<div>
				<h3 class="gridLabel"><%= link_to (p.first_name + " " + p.last_name), provider_path(p) %></h3>
			</div>
		</div>
		<div class="providerInfoRow">
			<div class="providerImage">
				<% if p.profile_image.blank? %>
				<%= link_to image_tag('no_photo_user.png', size: "75x100"), provider_path(p)%>
				<%else%>
				<%= link_to image_tag(url_for(action: :show_profile_image, id: p.id,
				controller: :providers), size: "75x100", alt: ""), provider_path(p) %>
				<%end%>

			</div>
			<div class="providerInfo">
				<div class="summaryBox label">
					<% if p.summary.blank? %>
					Summary has not yet been submitted for this provider.
					<%else%>
					<% if p.summary.to_s.length > 255%>
					<%= p.summary[0..255] %>...
					<%else%>
					<%= p.summary %>
					<%end%>
					<%end%>

				</div>
				<div class="infoBox">
					<%= render partial: 'layouts/ratings_control', locals: {p: p}%>
					<div class="avail">
						<%= render partial: 'layouts/avail_control', locals: {p: p}%>
					</div>
				</div>
			</div>
			<div class="rate">
				<div>
					<%= link_to provider_path(p) do %>
					<div class="gridLinkBox">
						View Provider
					</div>
					<%end%>
				</div>
				<div class="padToLinkBox">
					<%= render partial: 'layouts/rate_view', locals: {p: p}%>
				</div>
			</div>
		</div>
	</div>
	<%end%>
	<%= will_paginate @providers%>
</div>

app/views/layouts/_provider_profile_addend.html.erb
<div>
	<br />
	<h2 class="label">Profile Information</h2>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :summary, "Summary Of Services Offered:", { class: 'label'} %>
	</div>
	<div class="signUpMemoDiv">
		<%= f.text_area :summary, {cols: 40, rows: 30, class: 'memo_text_field'} %>
	</div>
	<div class="label">
		This is what will appear on search results to clients
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :profile_img, "Provide A Photo:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">
		<%= f.file_field :profile_img, {:data => { :max_file_size => 2.megabytes }, accept: 'image/png,image/gif,image/jpeg',class: 'text_field'} %>
	</div>
</div>
<% if !@provider.profile_image.blank? %>

<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= label_tag "", "Current Profile Photo:", class: 'label'%>
	</div>
	<div class="signUpInputDiv">
		<%= image_tag url_for(action: :show_profile_image, :id => @provider.id, :controller => :providers), size: "150x225" %>
	</div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<%end%>
<div>
	<br/>
	<h2 class="label">Service Methods Offered</h2>
</div>
<div class="signUpBlockDiv">
	<div class="signUpInputDiv">
		<%= f.check_box :service_by_phone, {class: 'check_box'}  %>
		<%= f.label :service_by_phone, "Phone", {class: 'check_box_label label'}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpInputDiv">
		<%= f.check_box :service_by_chat, {class: 'check_box'}  %>
		<%= f.label :service_by_chat, "Chat", {class: 'check_box_label label'}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpInputDiv">
		<%= f.check_box :service_by_email, {class: 'check_box'}  %>
		<%= f.label :service_by_email, "Email", {class: 'check_box_label label'}%>
	</div>
</div>
<div>
	<h2 class="label">Payment Information</h2>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :rate, "Charging Rate (US Dollars):", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :rate, {value: number_with_precision(f.object.rate, precision: 2), class: 'text_field', step: 0.01}%>
	</div>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :unit, "Per:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">
		<%= f.select :unit, options_for_select(['Hour', 'Minute', 'Session'], @provider.unit), {include_blank: 'Not Selected'}, {class: 'combo_box' }%>
	</div>
</div>

app/views/layouts/_provider_view.html.erb
<div class="providerInfoSingle">
	<div>
		<div class="column1">
			<div class="providerProfilePhoto">
				<% if @provider.profile_image.blank? %>
				<%= image_tag('no_photo_user.png', size: "150x200", class: 'providerFullImage')%>
				<%else%>
				<%= image_tag url_for(action: :show_profile_image, id: @provider.id,
				:controller => :providers), size: "150x200", class: 'providerFullImage'%>
				<%end%>
			</div>
			<div class="providerSchedAppt">
				<div class="statusBox">
					<% if @provider.status == 2 %>
					Available Now!
					<%elsif @provider.status == 3 %>
					Unavailable
					<%elsif @provider.status == 1%>
					Offline
					<%end%>
				</div>
				<%= render partial: 'layouts/check_provider_status/check_provider_status' %>
			</div>
		</div>
		<div class="column2">
			<div class="providerProfileInfo label">
				<div>
					<%= simple_format(@provider.summary) %>
				</div>
				<div class="providerPostInfo label">
					<div class="avail_singl avail">
						<%= render partial: 'layouts/avail_control', locals: {p: @provider}%>
					</div>
					<div class="providerRate">
						<%= render partial: 'layouts/rate_view', locals: {p: @provider}%>
					</div>

				</div>

			</div>
		</div>

		<div style="clear:both">
			<p>
				<%= link_to 'Back To Providers', providers_path%>
			</p>
		</div>
		<div class="commentSection">
			<% @provider.reviews.each do |review| %>
			<div class="providerRow">
				<div class="providerHeaderRow">
					<div>
						<h3 class="gridLabel">Reviewer: <%= review.client.first_name + " " + review.client.last_name%></h3>
					</div>
				</div>
				<div class="commentInfoRow label">
					<div class="commentHeaderRow">
						<%= render partial: '/layouts/single_rating_control', locals: {review: review} %>

						<div class="commentHeader">
							<% if !review.heading.blank? %>
							"<%= review.heading %>"
							<%else%>&nbsp;
							<%end%>
						</div>
					</div>
					<div class="floatClear"></div>
					<div class="reviewPortion">
						<%= review.review %>
					</div>

				</div>
				<div style="clear:both"></div>
			</div>
			<%end%>

		</div>

	</div>
</div>


app/views/layouts/_rate_view.html.erb
<div class="label rateBox">
	<% if p.rate.blank? || p.unit.blank? %>
	This provider has not yet set a rate
	<%else%>
	Rate: <%= number_to_currency(p.rate) %> Per <%= p.unit %>
	<%end%>
</div>

app/views/layouts/_ratings_control.html.erb
<div class="ratings label">
	<% if (p.reviews.count == 0) %>
	This provider has not yet been rated
	<% else %>
	<fieldset class="rating">
		<% (1..5).each do |i|%>
		<% if p.reviews.average(:rating) >= i %>
		<label for="star" class="ratingPos"></label>
		<%else%>
		<label for="star" class="ratingNeg"></label>
		<%end%>
		<% end %>
		<%= p.reviews.average(:rating) %> (<%= p.reviews.count %> Ratings)
	</fieldset>

	<%end%>
</div>

app/views/layouts/_security_info.html.erb
<div>
	<br/>
	<h2 class="label">Security Information</h2>
</div>
<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :password, "Password:", {class: 'label'}%>
	</div>
	<div class="signUpInputDiv">
		<%= f.password_field :password, {autocomplete: "off", class: 'text_field'} %>

	</div>
	<% if !resource.new_record? %>
	<div class="label">
		(Leave blank if you don't want to change it)
	</div>
	<%else%>
	<div class="label">
		(Passwords must contain at least 8 characters)
	</div>
	<%end%>
</div>

<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :password_confirmation, "Password Confirmation:", {class: 'label'} %>
	</div>
	<div class="signUpInputDiv">

		<%= f.password_field :password_confirmation, {autocomplete: "off", class: 'text_field'} %>
	</div>
</div>

app/views/layouts/_single_rating_control.html.erb
<fieldset class="rating">
	<% (1..5).each do |i|%>
	<% if review.rating >= i %>
	<label for="star" class="ratingPos"></label>
	<%else%>
	<label for="star" class="ratingNeg"></label>
	<%end%>
	<% end %>
</fieldset>

app/views/layouts/_submit.html.erb
<% if resource.new_record? %>
<div class="signUpBlockDiv">
	<div class="signButtonDiv">
		<%= f.submit "Sign up", { class: 'submit' } %>
	</div>
</div>
<% else %>
<div>
	<br/>
	<h2 class="label">Confirm Changes and Update</h2>
</div>
<% if @provider %>
<div class="signUpBlockDiv">
	<div class="signUpInputDiv">
		<%= f.check_box :public, {class: 'check_box'}  %>		
		<%= f.label :public, "Make this profile public to search results and allow clients to request information for sceduling appointments", {class: 'check_box_label label'}%>
	</div>
</div>
<%end%>
<div class="signUpBlockDiv">
	<div class="signUpBlockDiv">
		<div class="signUpLabelDiv">
			<%= f.label :current_password, "*Current Password:", {class: 'label'} %>
		</div>
		<div class="signUpInputDiv">

			<%= f.password_field :current_password, {autocomplete: "off", class: 'text_field'} %>

		</div>
		<div class="label">
			(We need your current password to confirm your changes)
		</div>
	</div>
	<div class="signButtonDiv">
		<%= f.submit "Update", {class: 'submit'} %>
	</div>
</div>
<%end%>

app/views/layouts/_tos_captcha.html.erb
<div class="signUpBlockDiv">
	<div class="signUpInputDiv">
		<%= f.check_box :terms_of_service, {class: 'check_box'}  %>
		<% if resource_name == "provider" %>
		
			<%else%>
			<%= f.label :terms_of_service, "*Checking this box indicates that you have read and agree to the #{resource_name.capitalize} Terms of Service and Privacy Policy", {class: 'check_box_label label'}%>
		<%end%>
	</div>
</div>
<div class="signUpInputDiv">
	<h2 class="label">Human Verification</h2>
	<br/>
</div>

<div class="signUpBlockDiv">
	<div class="signUpLabelDiv">
		<%= f.label :humanizer_answer, "*" + resource.humanizer_question, {class: 'label' } %>
	</div>
	<div class="signUpInputDiv">
		<%= f.text_field :humanizer_answer, class: 'text_field'%>
		<%= f.hidden_field :humanizer_question_id %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body class="header">
		
			<%= render 'layouts/header' %>
			<div class="container">
			<div>
				<%= yield %>
			</div>
			<%= render 'layouts/disclaimer'%>
		</div>
	</body>
</html>